[versions]
android-downloader = "3.0.1"
android-pdf-viewer = "2.8.2"
androidphotofilters = "1.0.2"
com-android-application = "8.2.1"
dexter = "6.2.2"
googlecode-isoparser = "1.1.22"
gson = "2.11.0"
itextg = "5.5.10"
itextg7 = "7.2.5"
kotlin-stdlib-jdk8 = "1.8.22"
library = "19.0.1"
lifecycle-livedata-ktx = "2.6.2"
multidex = "2.0.1"
okhttp3-integration = "4.13.1"
org-jetbrains-kotlin-android = "1.7.0"
benmanesversion = "0.45.0"
pdfium-android = "1.9.0"
safeargs = "2.5.3"
google_services_gradle = "4.3.15"
crashlytics_gradle = "3.0.3"
mobile-ffmpeg-full-gpl = "4.4.LTS"


compile_sdk_version = "34"
min_sdk_version = "24"
shimmerlayout = "1.1"
target_sdk_version = "34"

desugar = "2.0.4"
core-ktx = "1.13.1"
appcompat = "1.6.1"
material = "1.10.0"
constraintlayout = "2.1.4"
swipe_refresh_layout = "1.1.0"
legacy = "1.0.0"
sdp-ssp = "1.1.0"
fragment_ktx = "1.6.1"
lifecycle = "2.6.2"
navigation = "2.7.4"
recyclerview = "1.3.2"
exoplayer = "2.19.1"
room = "2.7.2"
viewpager2 = "1.0.0"
coroutines = "1.7.1"
glide = "5.0.5"
glide_webp = "2.3.4.14.2"
retrofit = "2.9.0"
datastore = "1.0.0"
timber = "5.0.1"
firebase = "33.1.0"
hilt = "2.56.2"
hilt_worker = "2.45"
lottie = "5.2.0"
camerax = "1.5.1"
cameraview = "2.7.1"

robolectric = "4.7.3"
carbon = "0.17.0"
gif-drawable = "1.2.29"
fontcalligraphy3 = "3.1.1"
fontviewpump = "2.0.3"
parcelize_runtime = "1.7.0"
expandable = "2.9.2"
junit-version = "4.13.2"
androidx-junit = "1.2.1"
espresso-core-version = "3.6.1"
transition = "1.5.1"
exifinterface = "1.4.0"
okhttp = "4.12.0"
agp = "8.7.3"
kotlin = "2.1.21"


[libraries]
verticalviewpager-library = { module = "com.github.castorflex.verticalviewpager:library", version.ref = "library" }
android-downloader = { module = "com.ixuea:android-downloader", version.ref = "android-downloader" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle-livedata-ktx" }
androidx-multidex = { module = "androidx.multidex:multidex", version.ref = "multidex" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
desugar = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugar" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
dexter = { module = "com.karumi:dexter", version.ref = "dexter" }
itextg = { module = "com.itextpdf:itextg", version.ref = "itextg" }
itextg7 = { module = "com.itextpdf:itext7-core", version.ref = "itextg7" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin-stdlib-jdk8" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
okhttp3-integration = { module = "com.github.bumptech.glide:okhttp3-integration", version.ref = "okhttp3-integration" }
pdfium-android = { module = "com.github.barteksc:pdfium-android", version.ref = "pdfium-android" }
shimmerlayout = { module = "xyz.peridy.shimmer:shimmerlayout", version.ref = "shimmerlayout" }
sdp = { group = "com.intuit.sdp",name= "sdp-android", version.ref = "sdp-ssp" }
ssp = { group = "com.intuit.ssp",name = "ssp-android", version.ref = "sdp-ssp" }
fragment_ktx = { group = "androidx.fragment",name = "fragment-ktx", version.ref = "fragment_ktx" }
viewmodel = { group = "androidx.lifecycle",name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle_runtime = { group = "androidx.lifecycle",name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
navigation_fragment = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation" }
navigation_ui = { group = "androidx.navigation",name = "navigation-ui-ktx", version.ref = "navigation" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
exo_core = { group = "com.google.android.exoplayer", name = "exoplayer-core", version.ref = "exoplayer" }
exo_ui = { group = "com.google.android.exoplayer", name = "exoplayer-ui", version.ref = "exoplayer" }
room_runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room_ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room_compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
viewpager2 = { group = "androidx.viewpager2",name = "viewpager2", version.ref = "viewpager2" }
coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines_core = { group = "org.jetbrains.kotlinx",name = "kotlinx-coroutines-core", version.ref = "coroutines" }
glide = { group = "com.github.bumptech.glide",name = "glide", version.ref = "glide" }
glide_webp = { group = "com.github.zjupure",name = "webpdecoder", version.ref = "glide.webp" }
glide_compiler = { group = "com.github.bumptech.glide", name = "compiler", version.ref = "glide" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
gson = { group = "com.squareup.retrofit2",name = "converter-gson", version.ref = "retrofit" }
datastore = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }
firebase_bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase" }
crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics-ktx" }
analytics = { group = "com.google.firebase", name = "firebase-analytics-ktx" }
configs = { group = "com.google.firebase", name = "firebase-config-ktx" }
hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt_compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
lottie = { group = "com.airbnb.android", name = "lottie", version.ref = "lottie" }
camera_lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "camerax" }
camerax_core = { group = "androidx.camera", name = "camera-core", version.ref = "camerax" }

robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
carbonview = { group = "tk.zielony", name = "carbon", version.ref = "carbon" }
gifdrawable = { group = "pl.droidsonroids.gif", name = "android-gif-drawable", version.ref = "gif-drawable" }
calligraphy = { group = "io.github.inflationx", name = "calligraphy3", version.ref = "fontcalligraphy3" }
viewpump = { group = "io.github.inflationx", name = "viewpump", version.ref = "fontviewpump" }
parcelize = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "parcelize_runtime" }
junit = { group = "junit", name = "junit", version.ref = "junit-version" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-junit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core-version" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }


[bundles]

